PT_params =   {'N': 32,
                            'activation': 1,
                            'weight_decay':1e-6,
                            'learning_rate': 1e-3,
                            'moving_avg':5,
                            'batch_size': 64,
                            'depth': 4,
                            'droput': 0.5,
                            'alpha': 1e-3,
                             'moving_avg':5,
                            'expansion_factor': 2,
                            'latent_size': 128,
                            'num_head': 8,
                             'z_dim': 32,
                            'num_cosines': 64,
                            'sine_cosine_emb':False, 
                            'patch_size': 4,
                            'sampling': 1,
                            'kappa': 0.5583529712369528,
                            'margin': 1.3010308436515978e-06,
                            'pv_input': 1,
                            'model_name':"iFPQ",
                            'out_postive':True,
                            'kappa': 0.5,
                            'clipping_value':0.05066637323875035,
                            'encoder_type': 'iFPQ',
                            'max_epochs': 500,
                            'max_days_autoregressive':8,
                            'period': '30T',
                            'rolling_window': 3,
                             'sine_cosine_emb':False, 
                            'SAMPLES_PER_DAY': 48,
                            'time_varying_known_feature': ['Ghi',  'Temperature','Dhi'], 
                            'time_varying_unknown_feature': ['NetLoad-Ghi'],
                            'targets':['NetLoad'],
                            'time_varying_known_categorical_feature': [ 'WEEK', 'DAYOFYEAR', 'HOUR'],
                            'emb_size':64,
                            'window_size': 96,
                            'horizon': 48}


UK_params =   {'N': 32,
                            'activation': 1,
                            'weight_decay':1e-6,
                            'learning_rate': 1e-3,
                            'moving_avg':5,
                            'batch_size': 64,
                            'depth': 4,
                            'z_dim': 32,
                            'droput': 0.5,
                            'alpha': 1e-3,
                             'moving_avg':5,
                            'expansion_factor': 2,
                            'latent_size': 128,
                            'num_head': 4,
                            'num_cosines': 64,
                            'sine_cosine_emb':False, 
                            'patch_size': 4,
                            'sampling': 1,
                            'kappa': 0.5583529712369528,
                            'margin': 1.3010308436515978e-06,
                            'pv_input': 1,
                            'model_name':"iFPQ",
                            'out_postive':True,
                            'kappa': 0.5,
                            'clipping_value':0.05066637323875035,
                            'encoder_type': 'iFPQ',
                            'max_epochs': 500,
                            'max_days_autoregressive':8,
                            'period': '30T',
                            'rolling_window': 3,
                             'sine_cosine_emb':False, 
                            'SAMPLES_PER_DAY': 48,
                            'time_varying_known_feature': ['Ghi'], 
                            'time_varying_unknown_feature': ['panel_temp_C', 'NetLoad-Ghi'],
                            'targets':['Load', 'NetLoad'],
                            'time_varying_known_categorical_feature': ['DAYOFWEEK', 'DAY', 'HOUR', 'Session'],
                            'emb_size':64,
                            'window_size': 96,
                            'horizon': 48}


hparams =   {
                'activation': 0,
                'weight_decay':1e-6,
                'learning_rate': 1e-3,
                'batch_size': 64,
                'depth': 2,
                'dropout': 0.25,
                'latent_size': 64,
                'num_head': 4,
                'vae_type':'vae',
                'clipping_value':0.05066637323875035,
                'encoder_type': 'MLPEncoder',
                'max_epochs': 2000,
                'max_days_autoregressive':8,
                'period': '30T',
                'dist_type':'normal',
                'SAMPLES_PER_DAY': 48,
                'time_varying_known_feature': ['Ghi',  'Temperature'], 
                'time_varying_unknown_feature': [],
                'targets':['NetLoad'],
                'time_varying_known_categorical_feature': ['WEEK', 'DAYOFYEAR', 'HOUR', 'Season'],
                'emb_size':28,
                'z_dim':32,
                'k':40,
                'window_size': 96,
                'horizon': 48,
                'hidden_size': 16,
                'conv_hidden_size': 32,
                'autotune': True,
                'stride': 16,
                'random_seed': 1,
                'encoder_hidden_size': 200,
                'context_size': 10,
                'decoder_hidden_size': 200,
                'encoder_n_layers': 2,
                'windows_batch_size': 1024,
            }

